---
variables:
  DUNECI_TEST_LABELS: quick

debian:10--gcc--expensive:
  # This image has Vc
  image: duneci/base:10
  script: duneci-standard-test
  # allow expensive tests
  variables: {DUNECI_TEST_LABELS: ""}
  # require AVX to properly test Vc
  tags: [duneci, "iset:avx"]
  # allowed to fail to e.g. do no hold up a merge when a runner supporting avx
  # is unavailable
  allow_failure: true

debian:10  gcc:c++17:
  image: duneci/base:10
  script: duneci-standard-test
  variables: {DUNECI_OPTS: /duneci/opts.gcc.c++17}
  tags: [duneci]

debian:9--gcc:
  image: duneci/base:9
  script: duneci-standard-test
  tags: [duneci]

debian:9--clang:
  image: duneci/base:9
  script: duneci-standard-test
  variables: {DUNECI_OPTS: /duneci/opts.clang}
  tags: [duneci]

ubuntu:16.04--gcc:
  image: duneci/base:16.04
  script: duneci-standard-test
  tags: [duneci]

ubuntu:16.04--clang:
  image: duneci/base:16.04
  script: duneci-standard-test
  variables: {DUNECI_OPTS: /duneci/opts.clang}
  tags: [duneci]
